const Router = require('koa-router')
const router = new Router({ prefix: '/dataStatistics'})

router.post('/getDataStatistics', ctx => {
  ctx.body = {
    code: '000000',
    mesg: '处理成功',
    time: new Date(),
    data: {
      fengxianyuan: {
        gongyeyuan: 20,
        weikuangku: 43,
        jiayouzhan: 81,
        weihuapin: 7,
        feishuipaikou: 46,
        feiqipaikou: 0
      },
      minfanmubiao: {
        shui: 1800,
        ziran: 230,
        heliu: 12,
        yiyuan: 130,
        xuexiao: 302
      }
    }
  }
})

router.post('/getPoints', async (ctx, next) => {
  ctx.body = {
    code: 0,
    message: '成功',
    data: [
      {
        "id": "134",
        "stationCode": null,
        "stationType": null,
        "areaCode": null,
        "weatherMn": null,
        "dataTime": "2022-10-27 17:00:00",
        "h2s": null,
        "voc": 31,
        "nh3": null,
        "temperature": null,
        "humidity": null,
        "pressure": null,
        "windSpeed": null,
        "windDirection": null,
        "lastUpTime": null,
        "pageNo": null,
        "pageSize": null,
        "rankValue": null,
        "startTime": null,
        "endTime": null,
        "stationName": "双泉西路010号",
        "longitude": 115.9567024,
        "datatimeValue": null,
        "latitude": 39.7515805,
        "typeValue": null,
        "position": null,
        "color": null,
        "index": null
      },
      {
        "id": "151",
        "stationCode": null,
        "stationType": null,
        "areaCode": null,
        "weatherMn": null,
        "dataTime": "2022-10-27 17:00:00",
        "h2s": null,
        "voc": 33,
        "nh3": null,
        "temperature": null,
        "humidity": null,
        "pressure": null,
        "windSpeed": null,
        "windDirection": null,
        "lastUpTime": null,
        "pageNo": null,
        "pageSize": null,
        "rankValue": null,
        "startTime": null,
        "endTime": null,
        "stationName": "高家坡路016号",
        "longitude": 115.9410849,
        "datatimeValue": null,
        "latitude": 39.7274015,
        "typeValue": null,
        "position": null,
        "color": null,
        "index": null
      },
      {
        "id": "136",
        "stationCode": null,
        "stationType": null,
        "areaCode": null,
        "weatherMn": null,
        "dataTime": "2022-10-27 17:00:00",
        "h2s": null,
        "voc": 28,
        "nh3": null,
        "temperature": null,
        "humidity": null,
        "pressure": null,
        "windSpeed": null,
        "windDirection": null,
        "lastUpTime": null,
        "pageNo": null,
        "pageSize": null,
        "rankValue": null,
        "startTime": null,
        "endTime": null,
        "stationName": "东风北里14号楼南",
        "longitude": 115.9558936,
        "datatimeValue": null,
        "latitude": 39.7570379,
        "typeValue": null,
        "position": null,
        "color": null,
        "index": null
      },
      {
        "id": "166",
        "stationCode": null,
        "stationType": null,
        "areaCode": null,
        "weatherMn": null,
        "dataTime": "2022-10-27 17:00:00",
        "h2s": null,
        "voc": 149,
        "nh3": null,
        "temperature": null,
        "humidity": null,
        "pressure": null,
        "windSpeed": null,
        "windDirection": null,
        "lastUpTime": null,
        "pageNo": null,
        "pageSize": null,
        "rankValue": null,
        "startTime": null,
        "endTime": null,
        "stationName": "城洪路",
        "longitude": 115.9680815,
        "datatimeValue": null,
        "latitude": 39.7115159,
        "typeValue": null,
        "position": null,
        "color": null,
        "index": null
      },
      {
        "id": "169",
        "stationCode": null,
        "stationType": null,
        "areaCode": null,
        "weatherMn": null,
        "dataTime": "2022-10-27 17:00:00",
        "h2s": null,
        "voc": 31,
        "nh3": null,
        "temperature": null,
        "humidity": null,
        "pressure": null,
        "windSpeed": null,
        "windDirection": null,
        "lastUpTime": null,
        "pageNo": null,
        "pageSize": null,
        "rankValue": null,
        "startTime": null,
        "endTime": null,
        "stationName": "宏塔路002号",
        "longitude": 115.9715792,
        "datatimeValue": null,
        "latitude": 39.7142586,
        "typeValue": null,
        "position": null,
        "color": null,
        "index": null
      },
      {
        "id": "137",
        "stationCode": null,
        "stationType": null,
        "areaCode": null,
        "weatherMn": null,
        "dataTime": "2022-10-27 17:00:00",
        "h2s": null,
        "voc": 39,
        "nh3": null,
        "temperature": null,
        "humidity": null,
        "pressure": null,
        "windSpeed": null,
        "windDirection": null,
        "lastUpTime": null,
        "pageNo": null,
        "pageSize": null,
        "rankValue": null,
        "startTime": null,
        "endTime": null,
        "stationName": "双泉滨河路026号",
        "longitude": 115.9544428,
        "datatimeValue": null,
        "latitude": 39.7616057,
        "typeValue": null,
        "position": null,
        "color": null,
        "index": null
      },
      {
        "id": "160",
        "stationCode": null,
        "stationType": null,
        "areaCode": null,
        "weatherMn": null,
        "dataTime": "2022-10-27 17:00:00",
        "h2s": null,
        "voc": -999,
        "nh3": null,
        "temperature": null,
        "humidity": null,
        "pressure": null,
        "windSpeed": null,
        "windDirection": null,
        "lastUpTime": null,
        "pageNo": null,
        "pageSize": null,
        "rankValue": null,
        "startTime": null,
        "endTime": null,
        "stationName": "杏花西里50号楼",
        "longitude": 115.9551329,
        "datatimeValue": null,
        "latitude": 39.7198900,
        "typeValue": null,
        "position": null,
        "color": null,
        "index": null
      },
      {
        "id": "159",
        "stationCode": null,
        "stationType": null,
        "areaCode": null,
        "weatherMn": null,
        "dataTime": "2022-10-27 17:00:00",
        "h2s": null,
        "voc": 22,
        "nh3": null,
        "temperature": null,
        "humidity": null,
        "pressure": null,
        "windSpeed": null,
        "windDirection": null,
        "lastUpTime": null,
        "pageNo": null,
        "pageSize": null,
        "rankValue": null,
        "startTime": null,
        "endTime": null,
        "stationName": "迎风南路027号",
        "longitude": 115.9518788,
        "datatimeValue": null,
        "latitude": 39.7211431,
        "typeValue": null,
        "position": null,
        "color": null,
        "index": null
      },
    ]
  }
})
module.exports = router